import './globals.css'
import Nav from "./header"
import Footer from "./footer"
import Sidebar from './nav'

export const metadata = {

  title: 'blackevn',
  description: 'Generated by create next app',

}

export default function RootLayout({

  children,

} : {

  children: React.ReactNode

}) {
  
  return (

    <html lang="en">

      <body>

        <Nav/>

        <div className='flex gap-10 h-[98vh] relative'>

          <Sidebar/>

          {children}
       
        </div>

     

      </body>

    </html>

  )
}
